services:
  ecommerceapp:
    image: ecommerceapp
    build:
      context: .
      dockerfile: EcommerceApp/Dockerfile
    depends_on:
      - ecommerceapi
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - app-network
    restart: unless-stopped

  ecommerceapi:
    image: ecommerceapi
    build:
      context: .
      dockerfile: EcommerceApi/Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=EcommerceDb;User Id=SA;Password=Contra123#;TrustServerCertificate=True;
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Contra123#
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Contra123#' -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  sql_data: